// SPDX-License-Identifier: MIT
// Copyright 2026 Tom F. <tomf@tomtomtech.net> (https://github.com/tomtom215)

//! Doctest harness for the quack-rs book and README.
//!
//! This crate has no code of its own. Under `cfg(doctest)` it includes one
//! empty module per Markdown page (generated by `build.rs`), documented by the
//! page's full text, so `cargo test --doc` compiles every Rust code block
//! against this working copy of quack-rs, and runs those not marked `no_run`.

#[cfg(doctest)]
include!(concat!(env!("OUT_DIR"), "/pages.rs"));
