// SPDX-License-Identifier: MIT
// Copyright 2026 Tom F. <tomf@tomtomtech.net> (https://github.com/tomtom215)

//! Generates `$OUT_DIR/pages.rs`: one empty module per Markdown page of the
//! book (plus the repository README), documented by the page itself, so every
//! fenced Rust block on a page becomes a doctest.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

/// Pages not compiled: the changelog quotes historical, superseded code.
const SKIPPED: &[&str] = &["changelog.md"];

fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries =
        fs::read_dir(dir).unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()));
    let mut paths: Vec<PathBuf> = entries
        .map(|e| e.expect("cannot read a directory entry").path())
        .collect();
    paths.sort();
    for path in paths {
        if path.is_dir() {
            collect(&path, out);
        } else if path.extension().is_some_and(|e| e == "md") {
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if !SKIPPED.contains(&name) {
                out.push(path);
            }
        }
    }
}

fn sanitise(rel: &str) -> String {
    rel.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

fn main() {
    let manifest =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"));
    let book_src = manifest
        .join("../src")
        .canonicalize()
        .expect("book/src must exist beside book/doctest");
    let repo_root = manifest
        .join("../..")
        .canonicalize()
        .expect("the repository root must exist");

    let mut pages = Vec::new();
    collect(&book_src, &mut pages);
    pages.push(repo_root.join("README.md"));

    let mut code =
        String::from("// @generated by book/doctest/build.rs: one module per Markdown page.\n");
    for (i, page) in pages.iter().enumerate() {
        let rel = page
            .strip_prefix(&repo_root)
            .expect("every page lives under the repository root")
            .to_str()
            .expect("page paths must be UTF-8");
        let abs = page.to_str().expect("page paths must be UTF-8");
        writeln!(
            code,
            "#[doc = include_str!({abs:?})]\n#[allow(non_snake_case)]\npub mod p{i}_{} {{}}",
            sanitise(rel)
        )
        .expect("writing to a String cannot fail");
        println!("cargo:rerun-if-changed={abs}");
    }
    // Re-run when a page is added or removed.
    println!("cargo:rerun-if-changed={}", book_src.display());

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo")).join("pages.rs");
    fs::write(&out, code).unwrap_or_else(|e| panic!("cannot write {}: {e}", out.display()));
}
