#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Regenerate book/src/reference/changelog.md from CHANGELOG.md.

The book page is a mirror of the root changelog with its own preamble. Keeping
it in sync by hand did not work: before this script existed the mirror was
~19 KB behind, and the published 0.16.0 entry was missing an entire
"Portability and feature-combination breakage" subsection.

Two deliberate transformations:

- The release-heading separator: the root uses an ASCII hyphen
  (`## [0.17.0] - 2026-08-21`, Keep a Changelog's form) and the book uses an em
  dash.
- Links to repository files (`[..](src/table/mod.rs)`) resolve from the
  repository root, where CHANGELOG.md lives, but not from
  `book/src/reference/`. They are rewritten to GitHub URLs.

Usage:
    scripts/sync-book-changelog.py            # rewrite the book page
    scripts/sync-book-changelog.py --check    # exit 1 if it is out of sync
"""

from __future__ import annotations

import difflib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "CHANGELOG.md"
DST = ROOT / "book" / "src" / "reference" / "changelog.md"

PREAMBLE = """# Changelog

All notable changes to quack-rs, mirrored from
[`CHANGELOG.md`](https://github.com/tomtom215/quack-rs/blob/main/CHANGELOG.md).

The format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).
quack-rs adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

<!-- Generated by scripts/sync-book-changelog.py. Edit CHANGELOG.md instead. -->

"""

# `## [0.17.0] - 2026-08-21` -> `## [0.17.0] — 2026-08-21`. Anchored to a
# release heading so a hyphen anywhere else in the body is untouched.
HEADING = re.compile(r"^(## \[[^\]]+\]) - (\d{4}-\d{2}-\d{2})$", re.MULTILINE)


# `](src/cast/)` -> `](https://github.com/.../tree/main/src/cast/)`. Only
# targets that start with a top-level repository path; URLs and `#anchors`
# are untouched.
REPO = "https://github.com/tomtom215/quack-rs"
REPO_LINK = re.compile(
    r"\]\(((?:src|tests|scripts|examples|benches|fuzz|docs|book|\.github)/[^)\s]*"
    r"|[A-Z][A-Z_]*\.md)\)"
)


def _repo_url(match: re.Match[str]) -> str:
    target = match.group(1)
    kind = "tree" if target.endswith("/") else "blob"
    return f"]({REPO}/{kind}/main/{target})"


def render() -> str:
    src = SRC.read_text(encoding="utf-8")
    try:
        body = src[src.index("## [") :]
    except ValueError:
        sys.exit(f"{SRC}: no '## [' release heading found")
    return PREAMBLE + REPO_LINK.sub(_repo_url, HEADING.sub(r"\1 — \2", body))


def main() -> int:
    want = render()
    if "--check" in sys.argv[1:]:
        have = DST.read_text(encoding="utf-8") if DST.exists() else ""
        if have == want:
            print(f"{DST.relative_to(ROOT)} is in sync with CHANGELOG.md")
            return 0
        print(f"{DST.relative_to(ROOT)} is OUT OF SYNC with CHANGELOG.md.")
        print("Run: scripts/sync-book-changelog.py")
        print()
        diff = difflib.unified_diff(
            have.splitlines(), want.splitlines(),
            "book (current)", "expected from CHANGELOG.md", lineterm="",
        )
        for i, line in enumerate(diff):
            if i >= 60:
                print("... (truncated)")
                break
            print(line)
        return 1
    DST.write_text(want, encoding="utf-8")
    print(f"wrote {DST.relative_to(ROOT)} ({len(want)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
